services:
  - type: web
    name: workout
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn weightlifting_tracker.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11